name: Build podman Image for the pythin app 

on:
  push:
    branches:
      - main  # adjust the branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman
          
      - name: Set new image tag
        run: |
          new_tag="${{ github.sha }}"
          export IMAGE_NAME=$QUAY_URL/$QUAY_REPOSITORY/sigstore-app:$new_tag

      - name: Build and push Podman image
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          QUAY_URL: ${{ secrets.QUAY_URL }}
          QUAY_REPOSITORY: ${{ secrets.QUAY_REPOSITORY }}
        
        run: |
           new_tag="${{ steps.increment_tag.outputs.new_tag }}"
           IMAGE_NAME=$QUAY_URL/$QUAY_REPOSITORY/sigstore-app:$new_tag
           podman build -t $IMAGE_NAME .
           podman login -u $QUAY_USERNAME -p $QUAY_PASSWORD $QUAY_URL
           podman push $IMAGE_NAME
