name: Build podman Image for the pythin app 

on:
  push:
    branches:
      - main  # adjust the branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Build Docker Image
        run: |
          podman build -t gha-python-image .
